name: hola-mundo 
on:
  push:
    branches: [ "main" ]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: python home/runner/work/curso-github-actions/hola_mundo.py