name: deploy
on: push
jobs: 
  deploy:
    name: deploy on cluster
    runs-on: ubuntu-latest
    steps:
      - name: Add code on server
        uses: actions/checkout@v3
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}